name: Build release zip

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build zip
      run: |
        # Create a directory with the plugin name
        mkdir wplaybook-all100-custom-block
        
        # Copy necessary files into the directory
        rsync -av --progress . wplaybook-all100-custom-block --exclude=wplaybook-all100-custom-block --exclude=.git --exclude=.github --exclude=.gitignore
        
        # Create the zip file
        zip -r wplaybook-all100-custom-block.zip wplaybook-all100-custom-block/
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: wplaybook-all100-custom-block.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
